# DocFX Filtering Rules
apiRules:
- include: # The namespaces to generate
    uidRegex: ^Preliy\.ExampleTemplate.*
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace
