# DocFX Filtering Rules
apiRules:
- include: # The namespaces to generate
    uidRegex: ^Preliy\.upm-template/.Runtime
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace
