name: Release

on: workflow_dispatch

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0          
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Create UPM Branches
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: preliy/create-upm-branch-action@development
        with:
          git-tag: upm/v${{ steps.semantic.outputs.new_release_version }}
