name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
          
      - name: Create UPM Branches  
        run: |
          git checkout master
          git config --local user.name Preliy
          git config --local user.email vikt.gaponenko@gmail.com
          git checkout -B upm 
          git mv $SAMPLES_DIR Samples~ &> /dev/null || echo $SAMPLES_DIR is not found
          git rm $SAMPLES_DIR.meta
          echo "Release Version; $TAG"
          git commit -m "release $TAG."
          git push -f origin upm
          git checkout -b upm@$TAG
          git push -f origin upm@$TAG
        env:
          TAG: v${{ steps.semantic.outputs.new_release_version }}              
          PKG_ROOT_DIR_PATH: ""
          SAMPLES_DIR: "Samples"
