name: Verify Unity License

on: workflow_dispatch

jobs:
  verifyUnityLicense:
    name: Verify License
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
              
              
            
